---
- name: Creating groups
  group: name="{{ item }}"
  with_items: groups_to_create
  sudo: yes
  tags: ['users','groups','configuration']

- name: Per-user group creation
  group: name="{{ item.username }}" gid="{{ item.uid if item.uid is defined else 1337 }}"
  with_items: users
  when: users_create_per_user_group
  sudo: yes
  tags: ['users','configuration']

- name: User creation
  user: name="{{ item.username }}"
        group="{{ item.username if users_create_per_user_group
            else users_group }}"
        groups="{{ item.groups | join(',') }}"
        shell={{ item.shell if item.shell is defined else users_default_shell }}
        password="{{ item.password if item.password is defined else '!' }}"
        comment="{{ item.name }}"
        uid="{{ item.uid if item.uid is defined else 1337 }}"
        createhome="{{ 'yes' if users_create_homedirs else 'no' }}"
  with_items: users
  sudo: yes
  tags: ['users','configuration']

- name: SSH keys
  authorized_key: user="{{ item.0.username }}" key="{{ item.1 }}"
  with_subelements:
    - users
    - ssh_key
  sudo: yes
  tags: ['users','configuration']

- name: add to sudoers list
  lineinfile: dest=/etc/sudoers.d/{{ item.username }}
              state=present
              create=yes
              line="{{ item.username }}   ALL=(ALL) NOPASSWD:ALL"
  when: item.is_sudo == True
  with_items: users
  sudo: yes
  tags: ['users','configuration']

- name: Deleted user removal
  user: name="{{ item.username }}" state=absent
  with_items: users_deleted
  sudo: yes
  tags: ['users','configuration']

- name: Deleted per-user group removal
  group: name="{{ item.username }}" state=absent
  with_items: users_deleted
  when: users_create_per_user_group
  sudo: yes
  tags: ['users','configuration']
